/* DATABASE PREPARATION */

-- CREATE DATABASE WITH DEFAULT SETTINGS
USE [master];

CREATE DATABASE [Sim4Sec_DW];

USE [Sim4Sec_DW];

SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

-- CREATE LOCATION DIMENSION
CREATE TABLE [Dim_Freg] (
	SK_FregID int PRIMARY KEY,
	FK_MunID 


